export { default as Navbar } from "./Navbar";
export { default as Hero } from "./Hero";
export { default as Partners } from "./Partners";
export { default as AboutUs } from "./AboutUs";
export { default as Courses } from "./Courses";
export { default as CTA } from "./CTA";
export { default as Graduted } from "./Graduated";
export { default as Testimonials } from "./Testimonial";
export { default as Footer } from "./Footer";
